version: "2"

services:
  alfresco:
    build:
      context: ./alfresco
      args:
        ALFRESCO_TAG: ${ALFRESCO_CE_TAG:-latest}
        DB: postgres
        SOLR_COMMS: https
        TRUSTSTORE_TYPE: JCEKS
        TRUSTSTORE_PASS: truststore
        KEYSTORE_TYPE: JCEKS
        KEYSTORE_PASS: keystore
        CERT_ALIAS: ssl.repo
    mem_limit: 7424m
    depends_on:
      - postgres
    environment:
      SERVER_NAME: ${CODESPACE_NAME:-localhost}
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
        -Dssl-keystore.password=keystore
        -Dssl-keystore.aliases=ssl-alfresco-ca,ssl-repo
        -Dssl-keystore.ssl-alfresco-ca.password=keystore
        -Dssl-keystore.ssl-repo.password=keystore
        -Dssl-truststore.password=truststore
        -Dssl-truststore.aliases=alfresco-ca,ssl-repo-client
        -Dssl-truststore.alfresco-ca.password=truststore
        -Dssl-truststore.ssl-repo-client.password=truststore"
      JAVA_OPTS: "
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.driver=org.postgresql.Driver
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
        -Dsystem.preferred.password.encoding=bcrypt10
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.port.ssl=8983
        -Dsolr.secureComms=https
        -Dsolr.baseUrl=/solr
        -Dindex.subsystem.name=solr6
        -Dalfresco.host=${SERVER_NAME}
        -Dalfresco.port=8080
        -Dshare.host=${SERVER_NAME}
        -Dshare.port=8080
        -Dshare.protocol=http"
    volumes:
      - ./keystores/alfresco:/usr/local/tomcat/keystore
      - alf-repo-data:/usr/local/tomcat/alf_data
      - alf-repo-logs:/usr/local/tomcat/logs

  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    mem_limit: 1856m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    volumes:
      - postgres-data:/var/lib/postgresql/data

  share:
    build:
      context: ./share
      args:
        SHARE_TAG: ${SHARE_TAG:-latest}
    mem_limit: 1856m
    environment:
      REPO_HOST: alfresco
      REPO_PORT: "8080"
      CSRF_FILTER_ENABLE: false
      CSRF_FILTER_REFERER: "https://localhost/.*|https://jubilant-happiness-pg4wvjjjw7f6gpg-8081.app.github.dev/share/.*"
      #CSRF_FILTER_REFERER: "http://localhost:8081/.*"
      #CSRF_FILTER_ORIGIN: "http://localhost:8081"
      JAVA_OPTS: "-Xms1728m -Xmx1728m"
    ports:
      - "8081:8080"
    volumes:
      - alf-share-logs:/usr/local/tomcat/logs

  solr6:
    build:
      context: ./search
      args:
        SEARCH_TAG: ${SEARCH_CE_TAG:-latest}
    mem_limit: 3712m
    environment:
      SOLR_JAVA_MEM: "-Xms2048m -Xmx2048m"
    volumes:
      - solr-data:/opt/alfresco-search-services/data

volumes:
  alf-repo-data:
  alf-repo-logs:
  alf-share-logs:
  postgres-data:
  solr-data:
